CC=

CFLAGS=-Wall -g

GCC_OFLAGS=-march=native -mavx2 -Ofast -finline-functions -funroll-loo
ps -ftree-vectorize -ftree-loop-vectorize -fopenmp -fopt-info-all=dist.gcc.optrpt 

all: genseq mask

mask.g: mask.c
	gcc $(CFLAGS) $(GCC_OFLAGS) $< -o $@

genseq: genseq.c
	$(CC) -march=native $(CFLAGS) -Ofast $< -o $@

clean:
	rm -Rf *~ genseq mask *.optrpt
